name: .NET

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  PREPARANDO:      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore
      run: |
        cd ./src/SC.FINANCIALMARKET
        dotnet restore
  
    - name: Build with dotnet
      run: |
        cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
        dotnet build --configuration Release
        
    - name: Dot net Publish
      run: |
                cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
                dotnet publish --configuration Release -o outputDirectory
    
    
    - name: Push Server
      uses: appleboy/scp-action@master
      env:
        HOST: 170.225.105.164
        USERNAME: Administrator
        PORT: 22
        KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAxAH7xj5KljTFD/+MAq9i7NNChE4XDNzv9iOcCqXGBF3euVvmZtacTgNtfii142JPgchA9Zpnos+rOQMFZi8e1Uw3plx+GBX+Xy+QksXI5CGCoNu78NR8dgfu1P+3vyNDQ+6G42Im9ieg8YKUBC65NknzJifrHip6avPGtfqlCNYb5CgSOhrClJMM/CVqRJ57c2BahH4MtNv3d9dMtDP8d0QATrn3dL4PiCmlDSR5snalr9iLwMS8BMwfuldL8w7HpbROl+NC3jERo8z7ADK2y94zGrTvwaKiRhQqUnPZeLsadZN4/97r/qTf1jX28aurX8hDOVeizjcPfzW6+YDjR550ZD+M2RQA1RXWkFDQZRbzytAaufRG0aGH+4mCwSj72+Iual5SPlNLLjJuzuT6VpuAysslZ7dagSs8c7N7dQXtW4csBxZGS7Y4Rz1sxt2xrmc8bcKQ8FlP5h1OAtaAl89DqB5RQ0SpNLtFo8cr4Rm15yQ/tcrgqATCGjB2qCUxAAAFkNGOxjPRjsYzAAAAB3NzaC1yc2EAAAGBAMQB+8Y+SpY0xQ//jAKvYuzTQoROFwzc7/YjnAqlxgRd3rlb5mbWnE4DbX4oteNiT4HIQPWaZ6LPqzkDBWYvHtVMN6ZcfhgV/l8vkJLFyOQhgqDbu/DUfHYH7tT/t78jQ0PuhuNiJvYnoPGClAQuuTZJ8yYn6x4qemrzxrX6pQjWG+QoEjoawpSTDPwlakSee3NgWoR+DLTb93fXTLQz/HdEAE6593S+D4gppQ0kebJ2pa/Yi8DEvATMH7pXS/MOx6W0TpfjQt4xEaPM+wAytsveMxq078GiokYUKlJz2Xi7GnWTeP/e6/6k39Y19vGrq1/IQzlXos43D381uvmA40eedGQ/jNkUANUV1pBQ0GUW88rQGrn0RtGhh/uJgsEo+9viLmpeUj5TSy4ybs7k+labgMrLJWe3WoErPHOze3UF7VuHLAcWRku2OEc9bMbdsa5nPG3CkPBZT+YdTgLWgJfPQ6geUUNEqTS7RaPHK+EZteckP7XK4KgEwhowdqglMQAAAAMBAAEAAAGACD1ZGy1VL1lKi3CfryE2VGRRIISz3VuQTtWSYrQzTc2wZjRhzCLrcTAdszb85nEkjH0hlfGGt8ZpGT1yRahncGoC0OCEgHi0N8YlGrZryoNKHX7/OJGGJeQReyzAya0uz7VAQGDI6IIj9uMZW8+nA4w6R3lYHe2FNefHi7DcrTFq/L1efsjPMzW3TwY3oGjVIbWEOJuf5x50GbqYQ98Hlu/p32Vb7LFsr7mocZP99a2dK3Y78b+Tc9Qs5UV0MOSHFxwnZ+o3Hasg4kTocfqcVkM2IX+ADDjfQ6PHpfQOuxtpfxhApo5F11M7/QcC7YCpEWk2+DQjt+GF5bebQdjD3y3j4/3UnTacpuKEU0SrwIzEjLJ3sbvN8/MZWrQ2OEbKN+A+3sMqgdplL4uBj1CFSHQ6M4I3DU0S9QGjOZ6KpudC3gkRHsBmZPlIm7hBpSFxqH91xYEz4BoQ91NUkk8ZSiZULADbo8Qjdc06nml052/WpNg3i9u3hUkhash/ijFdAAAAwQDK9CC4cO7uec7wCbSWqTU/NcFCkPxbRAGIlWw+i25iK//MW9hwNf03VisNpoECSXu44v5QSm7c9k7OYudlHfsvG2YAoSXNXcI1e4pwtooNUCVTs0333rAQMNJ/34Cbsc2wfvNURmL4CbgD9LWxpxdUNO/3oVMLQHLD+4ORj84RAqVXKT2vJVo0uzFKd/4n0JLX9WzEqAeXiKstb0vBjdi5kV+gNqHZ5F4DdS1f7fDS1FGHV5fjCRn0pQCEcbqkKVUAAADBAPUs64yXgS8KPrr0g/0+ls8XbU9OzRbcWU/RLaxaGysCncGNDtz4qdan9KBdPLeIO1i++bubbO7yNazzekcWQnwTYmG2aK/Q904Q5mXpPum+55HKx3Vi7nyIx+ebtPSwMB8nZiIycvONJbSUSxjFNA7TVvroaceW4ju4XjSWYYnXLvWSQ50ZSogKCzLBsNt3abA6qybOlkTXuAiaIUmB8VibbGsxzx04DE+SlSXFFxF/w6nkWrEX40ac7LMvAn2auwAAAMEAzKlZMCDS4rNdDCzdVEFQUZAw3hxN/pj8oB5xGtZ/SYaf92qzeDV75enXNTI3KMzfzlPeOGfAarjuVbJRqNfuNEnVKDHslvtQYXaP6yAEOEyEJEwwN7K7sFdZ+ZRTvy7gfWga+1JRHqUnzb2hW8vnRSH1PiU2g2b5PU8qI9D5E20F0+Oz7hMtoPMdSHB05CSyrDS4NvkN+CwZROgwwMtxrLM09yL+a5NUJI+D1ILvR8X71vSXa+k4klChd428ZS8DAAAAFXJvZHJpQERFU0tUT1AtNTUxQ0lCNgECAwQF
      with:
        source: "./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/outputDirectory"
        target: "C:\\Projects\\SignumCapital\\SIGNUM.FINANCIALMARKET"

