name: .NET

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  PREPARANDO:      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    #- name: Restore
    #  run: |
    #    cd ./src/SC.FINANCIALMARKET
    #    dotnet restore
  
    - name: Build with dotnet
      run: |
        cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
        dotnet build --configuration Release
        
    - name: Dot net Publish
      run: |
                cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
                dotnet publish --configuration Release -o outputDirectory

    - name: Compactando pasta
      run: |
              tar -czvf ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/compact.tar.gz ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/outputDirectory

    - name: Push Server
      uses: airvzxf/ftp-deployment-action@latest
      with:
        # FTP Server.
        server: 173.225.105.164
        # FTP User.
        user: Adm
        # FTP Password.
        password: 1996Rodrigo
        # Local directory.
        local_dir: /src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/compact.tar.gz
        # Remote directory.
        remote_dir: ./SignumCapital/SIGNUM.FINANCIALMARKET

  
