name: .NET

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  PREPARANDO:      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore
      run: |
        cd ./src/SC.FINANCIALMARKET
        dotnet restore
  
    - name: Build with dotnet
      run: |
        cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
        dotnet build --configuration Release
        
    - name: Dot net Publish
      run: |
                cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
                dotnet publish --configuration Release -o outputDirectory
    
    
    - name: Push Server
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: 173.225.105.164
        REMOTE_USER: Administrator
        SOURCE: "./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/outputDirectory"
        TARGET: "C:\\Projects\\SignumCapital\\SIGNUM.FINANCIALMARKET"

