name: .NET

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  PREPARANDO:      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore
      run: |
        cd ./src/SC.FINANCIALMARKET
        dotnet restore
  
    - name: Build with dotnet
      run: |
        cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
        dotnet build --configuration Release
        
    - name: Dot net Publish
      run: |
                cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
                dotnet publish --configuration Release -o outputDirectory

    - name: Push Server
      uses: matheusvanzan/sshpass-action@v1
      with:
        # SSHPASS host
        host: 173.225.105.164
        # SSHPASS username
        username: Administrator
        # SSHPASS password
        password: SoVi@#2020
        # SSHPASS commands to run
        run: |
                %SYSTEMROOT%\System32\inetsrv\appcmd stop apppool /apppool.name:"SignumCapital.FINANCIALMARKET"                
                scp ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/outputDirectory Administrator@173.225.105.164:C:\Projects\SignumCapital\SIGNUM.FINANCIALMARKET                
                %SYSTEMROOT%\System32\inetsrv\appcmd start apppool /apppool.name:"SignumCapital.FINANCIALMARKET"
