name: .NET

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:
  PREPARANDO:      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    #- name: Restore
    #  run: |
    #    cd ./src/SC.FINANCIALMARKET
    #    dotnet restore
  
    #- name: Build with dotnet
    #  run: |
    #    cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
    #    dotnet build --configuration Release
        
    - name: Publicando projeto
      run: |
                cd ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API
                dotnet publish --configuration Release -o outputDirectory

    - name: Compactando pasta
      run: |
              mkdir ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/compact
              tar -czvf ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/compact/compact.tar.gz -C ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/outputDirectory .

    - name: Enviando para servidor
      uses: airvzxf/ftp-deployment-action@latest
      with:
        # FTP Server.
        server: 173.225.105.164
        # FTP User.
        user: rodrigo
        # FTP Password.
        password: 1996Rodrigo
        # Local directory.
        local_dir: ./src/SC.FINANCIALMARKET/SC.FINANCIALMARKET.API/compact
        # Remote directory.
        remote_dir: ./SignumCapital/SIGNUM.FINANCIALMARKET

    - name: Preparando Serviço
      uses: matheusvanzan/sshpass-action@v1
      with:
        # SSHPASS host
        host: 173.225.105.164
        # SSHPASS username
        username: Administrator
        # SSHPASS password
        password: SoVi@#2020
        # SSHPASS commands to run
        run: |
                %SYSTEMROOT%\System32\inetsrv\appcmd stop apppool /apppool.name:"SignumCapital.FINANCIALMARKET"                
                cd C:\Projects\SignumCapital\SIGNUM.FINANCIALMARKET
                tar -xzvf compact.tar.gz
                %SYSTEMROOT%\System32\inetsrv\appcmd start apppool /apppool.name:"SignumCapital.FINANCIALMARKET"
  
